project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: ".."
preserve_hierarchy: false
files:
  - source: src/XIVLauncher.Core/Resources/Localization/Strings.resx
    translation: src/XIVLauncher.Core/Resources/Localization/Strings.%two_letters_code%.resx
